---
title: "535 HW5"
author: "Kelly DeBie"
date: "2022-11-30"
output: word_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Homicide Data for 50 U.S. Cities

```{r, message=FALSE, output=FALSE}
## Packages to be installed for this assignment  
library(tidyverse)
library(forcats)  
library(broom)  
library(purrr)  
library(ggplot2)
library(ggthemes) 
library(scales)  
library(tigris)
```

Read in the Data 

```{r}
homicides <- read.csv("C:/Users/k_deb/OneDrive - Colostate/ERHS 535/homicide-data.csv")  
homicides$city_name <- paste(homicides$city, homicides$state, sep=",")  

```

Add variable for unsolved homicides

```{r}
homicides$disp_unsolved = (homicides$disposition != "Closed by arrest") 
head(homicides)

```


```{r fig.height=10, fig.width=14}
denver_map<- tracts("CO", "Denver") 
denver_homicides <- 
  filter(homicides, city_name=="Denver,CO")
head(denver_homicides)
denver <- ggplot() +
  geom_sf(data=denver_map) +
  geom_point(data=denver_homicides, aes(x=lon, y=lat, col=victim_race)) +
  labs(x= "Longitude", y="Latitude", title= "Homicides in Denver, Colorado", col= "Victim Race") +
  theme_few()
denver + facet_wrap(~disp_unsolved, ncol=1)

###still need to adjust facet labels

```

